apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: auth
    template:
        metadata:
            labels:
                app: auth
        spec:
            containers:
                - name : auth
                  image: rampooco/auth
                #   livenessProbe:
                #     httpGet:
                #         path: /api/users/liveness-readiness
                #         port: 3000
                #     initialDelaySeconds: 70
                #     timeoutSeconds: 80
                  readinessProbe:
                    httpGet:
                        path: /api/users/liveness-readiness
                        port: 3000
                    initialDelaySeconds: 70
                    timeoutSeconds: 80 
                  env :
                    - name : MONGO_URI
                      value : 'mongodb://auth-mongo-clusterip:27017/auth'
                    - name : JWT_KEY
                      valueFrom:
                        secretKeyRef:
                            name: jwt-secret
                            key : JWT_KEY
                #   image: us.gcr.io/ticketing-app-279804/auth
---

apiVersion : v1
kind : Service
metadata : 
    name : auth-clusterip-service
spec: 
    selector:
        app: auth
    ports:
        - name : auth
          protocol : TCP
          port: 3000
          targetPort: 3000