apiVersion : networking.k8s.io/v1beta1
kind : Ingress
metadata : 
    name : ingress-srv
    annotations :
        kubernetes.io/ingress.class : nginx
        nginx.ingress.kubernetes.io/use-regex : 'true'
spec :
    rules :
        - host : ticketing.dev
          http :
            paths :
                - path : /api/users/?(.*)
                  backend :
                    serviceName : auth-clusterip-service
                    servicePort : 3000
                - path : /api/tickets/?(.*)
                  backend :
                    serviceName : tickets-clusterip-service
                    servicePort : 3000
                - path : /api/orders/?(.*)
                  backend :
                    serviceName : orders-clusterip-service
                    servicePort : 3000
                - path : /?(.*)
                  backend :
                    serviceName : client-clusterip-service
                    servicePort : 3000
                
              