version: "3"

services:
  redis:
    image: redis:7.0.4
    networks:
      - ws

  app:
    build: 
      context: .
    image: rampooco/websocket
    container_name: websocket
    restart: on-failure
    ports:
      - 8080:8080
    depends_on: 
      - redis
    networks: 
      - ws

networks:
  ws:
    driver: bridge